defaults: &defaults
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *defaults
  database: testapp_development

test:
  <<: *defaults
  database: testapp_test

production:
  <<: *defaults
  database: testapp_production
